# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 09:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0007_auto_20161203_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='belong_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collect',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 9, 41, 6, 560557)),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='housetype',
            field=models.CharField(choices=[('三室一厅两卫', '三室一厅两卫'), ('一室一厅一卫', '一室一厅一卫'), ('三室两厅两卫', '三室两厅两卫'), ('四室两厅两卫', '四室两厅两卫'), ('三室一厅一卫', '三室一厅一卫'), ('二室一厅一卫', '二室一厅一卫')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('保密', '保密'), ('男', '男'), ('女', '女')], default='保密', max_length=10),
        ),
    ]
