# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_video_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vocation',
            field=models.CharField(choices=[('author', 'author'), ('normal', 'normal')], default='normal', max_length=10),
        ),
    ]
